### ISSUE TITLE
Feature request: rsync

### ISSUE THREAD

**Issue by aaronbauman** [terminus-plugin-project/terminus-filer-plugin#9]
When copying to and from Pantheon environments, I frequently find myself issuing an rsync command like the following:

  ```rsync -avz -e 'ssh -p 2222' pantheon-user@pantheon.sftp.drush.in:~/files local/path/files/```

Would love to have this wrapped up in a `filer` command like

  ```terminus filer:rsync site.env [source] [destination]```

**Comment by uberhacker** [comment]
Hey @aaronbauman:  There is a rsync plugin.  Check out https://github.com/pantheon-systems/terminus-rsync-plugin.

**Comment by aaronbauman** [comment]
Thanks, should have googled first 🙃
